---
#- name: "Load customer variables"
#  include_vars:
#    file: customer-profile.yml

- name: "Pull the Joomla Image"
  docker_image:
    name: joomla
    source: pull

- name: "Create and run the Joomla container"
  docker_container:
    env:
      JOOMLA_DB_HOST: "{{ lookup('dig', ansible_host) }}:3306"
      JOOMLA_DB_USER: "root"
      JOOMLA_DB_PASSWORD: "ucProject123"
    name: joomla
    image: joomla
    ports:
      - "8084:80"
